databases:
  - name: cumulus-db
    plan: free
    databaseName: cumulus
    user: cumulus

services:
  - type: web
    name: cumulus-web
    plan: free
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "poetry run gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cumulus-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "4"
